### ISSUE TITLE
Didn't work for my location

### ISSUE THREAD

**Issue by xdCL** [GreenMeteor/humhub-weather-module#14]
There is anyway to use another weather API in this module?

like this? https://www.meteored.cl/api/

Thanks!

**Comment by ArchBlood** [comment]
Could you provide more information, such as what location that isn't working?

As for the answer to your question, this module isn't setup to use any other API other than the one from https://weatherwidget.io & https://forecast7.com so if the API isn't working right then you'll need to contact one of these websites about the issue.

As for integrating the Meteored API, I'm not too sure on how I'd go about doing so, because looking at how they've got their end setup they're using XML & JSON domain calls which have to be encoded before use in HumHub & Yii 2, as is the module is very simple to use and I nor many others that use it have many problems with it.
